In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr=np.ones(10)+4
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np


<module 'numpy' from 'C:\\Users\\HP\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [14]:
np.random.rand(25)

array([0.01636834, 0.17378556, 0.67771361, 0.21321363, 0.0505121 ,
       0.15617227, 0.60713836, 0.65864151, 0.70057785, 0.22542698,
       0.40011596, 0.37239303, 0.03384612, 0.77109258, 0.46613935,
       0.78880207, 0.31203382, 0.41739018, 0.91338008, 0.61285163,
       0.76793645, 0.79499395, 0.75166827, 0.53070925, 0.6885991 ])

In [21]:
np.linspace(0,1,100).reshape(10,10)


array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [22]:
arr=np.arange(1,26).reshape(5,5)

In [23]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
arr[3][4]

20

In [33]:
arr[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [34]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])