In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
with open ("D:/COURSES/Python for Machine Learning & Data Science Masterclass/1 - Introduction to Course/18-Naive-Bayes-and-NLP/One.txt") as text:
    str=text.read()

In [25]:
str.lower().split()


['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [26]:
one_uni=set(str.lower().split()
)

In [27]:
one_uni

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [28]:
with open ("D:/COURSES/Python for Machine Learning & Data Science Masterclass/1 - Introduction to Course/18-Naive-Bayes-and-NLP/Two.txt") as text:
    str2=text.read()

In [40]:
two_uni=set(str2.lower().split()
)

In [41]:
total_uni=set()

In [42]:
total_uni.update(one_uni)

In [43]:
total_uni.update(two_uni)

In [44]:
total_uni

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [46]:
uni_elems=dict()

In [47]:
i=0

for word in total_uni:
    uni_elems[word]=i
    i=i+1

In [48]:
uni_elems

{'are': 0,
 'popular': 1,
 'a': 2,
 'waves': 3,
 'dogs': 4,
 'pets': 5,
 'surfing': 6,
 'catching': 7,
 'animals': 8,
 'is': 9,
 'fun': 10,
 'canine': 11,
 'sport': 12,
 'story': 13,
 'this': 14,
 'water': 15,
 'about': 16,
 'furry': 17,
 'our': 18}

In [61]:
with open("D:/COURSES/Python for Machine Learning & Data Science Masterclass/1 - Introduction to Course/18-Naive-Bayes-and-NLP/One.txt") as text:
    str=text.read().lower().split()
# one_occur=uni_elems[word].
str

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [62]:
one_occur=[0]*len(total_uni)
two_occur=[0]*len(total_uni)
all_words=['']*len(total_uni)

In [63]:
for word in str:
    one_occur[uni_elems[word]]+=1

In [64]:
one_occur

[1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1]

In [65]:
with open("D:/COURSES/Python for Machine Learning & Data Science Masterclass/1 - Introduction to Course/18-Naive-Bayes-and-NLP/Two.txt") as text:
    str2=text.read().lower().split()

In [66]:
for word in str2:
    two_occur[uni_elems[word]]+=1

In [67]:
two_occur

[0, 1, 1, 1, 0, 0, 2, 1, 0, 3, 1, 0, 1, 1, 1, 1, 1, 0, 0]

In [68]:
pd.DataFrame(data=[one_occur,two_occur],columns=uni_elems)

are  popular  a  waves  dogs  pets  surfing  catching  animals  is  fun  \
0    1        0  1      0     2     1        0         0        1   1    0   
1    0        1  1      1     0     0        2         1        0   3    1   

   canine  sport  story  this  water  about  furry  our  
0       1      0      1     1      0      1      1    1  
1       0      1      1     1      1      1      0    0

In [70]:
uni_elems["dogs"]

4

In [71]:
text=["This is a line",
     "This is another line",
     "Completely different line"]

In [78]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,TfidfVectorizer

In [95]:
# cv=CountVectorizer(stop_words='english') 
cv=CountVectorizer() 
# help(cv)

In [96]:
sparse_matrix=cv.fit_transform(text)

In [97]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [99]:
tfidft=TfidfTransformer()

In [103]:
result=tfidft.fit_transform(sparse_matrix)

In [104]:
result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [106]:
tfidfv=TfidfVectorizer()

In [109]:
tfidfv.fit_transform(text).todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])