In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('D:\\COURSES\\Python for Machine Learning & Data Science Masterclass\\1 - Introduction to Course\\08-Linear-Regression-Models\\Advertising.csv')

In [6]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
X=df.drop('sales',axis=1)
y=df['sales']

In [8]:
from sklearn.preprocessing import PolynomialFeatures


In [9]:
poly_converter=PolynomialFeatures(degree=3,include_bias=False)

In [10]:
poly_features=poly_converter.fit_transform(X)

In [11]:
poly_features.shape

(200, 19)

In [12]:
X.shape

(200, 3)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [15]:
from  sklearn.preprocessing import StandardScaler


In [16]:
scaler=StandardScaler()

In [17]:
scaler.fit(X_train) #don't ever do the fit on X_test set as we dont want to reveal any information of test
#otherwise it would cause data leakage
#fit basically uses mean and std on data

StandardScaler()

In [18]:
X_train=scaler.transform(X_train)

In [19]:
X_test=scaler.transform(X_test)

In [20]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
from sklearn.linear_model import Ridge

In [22]:
ridge_model=Ridge(alpha=10) #alpha is basically lambda parameter in regularizing addition term

In [23]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [24]:
test_predictions=ridge_model.predict(X_test)

In [25]:
# MAE
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [26]:
mean_absolute_error(test_predictions,y_test)

0.5774404204714183

In [27]:
#RMSE
np.sqrt(mean_squared_error(test_predictions,y_test))

0.8946386461319685

In [28]:
#Now using cross validation in ridge regression

In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
help(RidgeCV)

Help on class RidgeCV in module sklearn.linear_model._ridge:

class RidgeCV(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidgeCV)
 |  RidgeCV(alphas=(0.1, 1.0, 10.0), *, fit_intercept=True, scoring=None, cv=None, gcv_mode=None, store_cv_values=False, alpha_per_target=False)
 |  
 |  Ridge regression with built-in cross-validation.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  By default, it performs efficient Leave-One-Out Cross-Validation.
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alphas : array-like of shape (n_alphas,), default=(0.1, 1.0, 10.0)
 |      Array of alpha values to try.
 |      Regularization strength; must be a positive float. Regularization
 |      improves the conditioning of the problem and reduces the variance of
 |      the estimates. Larger values specify stronger regularization.
 |      Alpha corresponds to ``1 / (2C)`` in other linear models such as
 |

In [31]:
ridge_cv_model=RidgeCV(alphas=(0.1, 1.0, 10.0))

In [32]:
ridge_cv_model.fit(X_train,y_train) #it will be doing cross validationr

RidgeCV()

In [33]:
test_predictions= ridge_cv_model.predict(X_test)

In [34]:
mean_absolute_error(test_predictions,y_test)

0.42737748843373746

In [35]:
np.sqrt(mean_squared_error(test_predictions,y_test))

0.6180719926921404

In [36]:
#better performance of model as err is reduced

In [37]:
ridge_cv_model.best_score_ #least error

-0.37770668487073494

In [38]:
ridge_cv_model.alpha_ #best scoring alpha

0.1

In [39]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [40]:
from sklearn.metrics import get_scorer_names

In [41]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',

In [42]:
ridge_cv_model=RidgeCV(alphas=(0.1, 1.0, 10.0),scoring="neg_mean_absolute_error") #now neg_mean_squared_error will be used 
#for performance

In [43]:
ridge_cv_model.fit(X_train,y_train) #it will be doing cross validationr
test_predictions= ridge_cv_model.predict(X_test)

In [44]:
mean_absolute_error(test_predictions,y_test)

0.42737748843373746

In [45]:
np.sqrt(mean_squared_error(test_predictions,y_test))

0.6180719926921404

In [46]:
from sklearn.linear_model import LassoCV

In [47]:
lasso_cv_model=LassoCV(eps=0.01,n_alphas=100,max_iter=1000)

In [48]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(eps=0.01)

In [49]:
test_predictions=lasso_cv_model.predict(X_test)

In [50]:
mean_absolute_error(test_predictions,y_test)

0.5159788188265405

In [51]:
np.sqrt(mean_squared_error(test_predictions,y_test))

0.7615440303260841

In [52]:
lasso_cv_model.coef_  #look at the trend how it is ignoring most of the features

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [53]:
from sklearn.linear_model import ElasticNetCV

In [67]:
elastic_cv_model=ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1],eps=0.001,max_iter=100000,n_alphas=100)

In [68]:
elastic_cv_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [69]:
test_predictions=elastic_cv_model.predict(X_test)

In [70]:
elastic_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [71]:
elastic_cv_model.alpha_ #best performing alpha

0.004943070909225827

In [72]:
elastic_cv_model.l1_ratio_ #best performing ratio 

1.0

In [73]:
#its showing lasso is better as 
# For l1_ratio = 0 the penalty is an L2 penalty. For l1_ratio = 1 it is an L1 penalty.